name: stylelint
on: [pull_request]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      - name: Install dependencies
        run: pnpm install stylelint stylelint-config-standard stylelint-config-recess-order stylelint-config-prettier
      - name: install reviewdog
        uses: reviewdog/action-setup@v1
      - name: stylecheck
        run: pnpm stylelint "**/*.css" --no-color --fix | reviewdog -f="stylelint" -name="stylelint" -reporter="github-pr-review" -level="error" -filter-mode="nofilter" -fail-on-error="false"