name: code_analysis
on: [pull_request]
jobs:
  code_analysis:
    name: runner
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: pnpm install stylelint stylelint-config-standard stylelint-config-recess-order stylelint-config-prettier
        
      - name: install reviewdog
        uses: reviewdog/action-setup@v1
      - name: stylecheck
        run: pnpm stylelint "**/*.css" --no-color | reviewdog -f=stylelint -name=stylelint -reporter=github-pr-review -fail-on-error=true
