name: reviewdog
on: [pull_request]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: |
            package-lock.json
      - run: npm ci
      - uses: reviewdog/action-setup@v1
      - run: reviewdog -version
      - name: stylelint
        env:
          # reviewdogはこの環境変数でTokenを参照する
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx stylelint "**/*.css" --no-color --fix \
            | reviewdog -f="stylelint" -name="stylelint" -reporter="github-pr-check" -level="error" -filter-mode="nofilter" -fail-on-error="false"
