name: code_analysis
on: [pull_request]
jobs:
  code_analysis:
    name: runner
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: depencies
        run: npm install stylelint stylelint-config-standard stylelint-config-recess-order stylelint-config-prettier
        
      - name: install reviewdog
        uses: reviewdog/action-setup@v1
      - name: reviewdog
        run: reviewdog -reporter=github-pr-check
