name: code_analysis
on: [pull_request]
jobs:
  code_analysis:
    name: runner
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: install reviewdog
        uses: reviewdog/action-setup@v1
      - name: stylecheck
        run: pnpm stylelint "**/*.css" --no-color --fix | reviewdog -f="stylelint" -name="stylelint" -reporter="github-pr-check" -level="error" -filter-mode="nofilter" -fail-on-error="false"
      - name: commit and push
        run: |
          git config --global user.name 'Github Actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "Changed by github-actions"; \
            git push dev; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}